name: "link_pred_temporal"
task: "temporal_link_prediction"
seed: 123

MODEL:
  model: "VGRNN"

DATASET:
  dataset: "fb"
  TEMPORAL:
    use_feat: False
    test_len: 1

LOSS:
  loss: 'MSEloss'

TRAIN:
  max_epochs: 1000
  log_epoch: 10
  batch_size: 64
  initial_lr: 5e-5

  OPTIMIZER:
    type: "ADAM"

ATTACK:
  method: "random"
  ptb_rate: 0.0
  attack_data_path: "./data/attack_data"
  new_attack: True

TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 4
    num_nodes: 20
    inner_prod: False
    filter_size: 2
