name: "link_pred_gae"
task: "static_link_prediction"

MODEL:
  model: "VGAE"
  encoder: "linear"

DATASET:
  dataset: "cora"
  
LOSS:
  loss: 'BCEWithLogitsLoss'

TRAIN:
  max_epochs: 100
  batch_size: 32
  initial_lr: 0.01
  OPTIMIZER:
    type: "ADAM"

ATTACK:
  method: "random"
  ptb_rate: 0.5
    
TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 1433

  