name: "link_pred_temporal"
task: "temporal_link_prediction"
seed: 123

MODEL:
  model: "VGRNN"

DATASET:
  dataset: "fb"
  TEMPORAL:
    use_feat: False
    test_len: 3

TRAIN:
  max_epochs: 1500
  log_epoch: 10
  batch_size: 64
  initial_lr: 0.01
  OPTIMIZER:
    type: "ADAM"

ATTACK:
  method: "random"
  ptb_rate: 0.5
  attack_data_path: "/home/randomgraph/data/attack_data"
  new_attack: True

TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 4
    num_nodes: 20
    inner_prod: False
    filter_size: 2
