name: "link_pred_temporal"
task: "temporal_link_prediction"
seed: 123

MODEL:
  model: "VGRNN"

DATASET:
  dataset: "fb"
  use_feat: False

  
LOSS:
  loss: 'MSEloss'

TRAIN:
  max_epochs: 1000
  log_epoch: 10
  batch_size: 64
  initial_lr: 0.01
  OPTIMIZER:
    type: "ADAM"

TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 4
    num_nodes: 20
    inner_prod: False
    filter_size: 2
