name: "link_pred_gae"
task: "static_link_prediction"

MODEL:
  model: "GAE"
  encoder: "GCN"

DATASET:
  dataset: "reddit"
  TEMPORAL:
    use_feat: False
    test_len: 3
  STATIC:
    merged_data_path: "merged_data"

TRAIN:
  max_epochs: 1500
  batch_size: 32
  initial_lr: 0.01
  OPTIMIZER:
    type: "ADAM"

ATTACK:
  method: "random"
  ptb_rate: 0.0
  attack_data_path: "attack_data"
  new_attack: False
    
TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 10984

LOGGING:
  log_file: "log.txt"
  model_file: "model.pt"
  