name: "link_pred_gae"
task: "static_link_prediction"

MODEL:
  model: "VGAE"
  encoder: "linear"

DATASET:
  dataset: "enron10"

TRAIN:
  max_epochs: 100
  batch_size: 32
  initial_lr: 0.01
  OPTIMIZER:
    type: "ADAM"

ATTACK:
  method: "random"
  ptb_rate: 0.2
  attack_data_path: "attack_data"
  new_attack: True
    
TASK_SPECIFIC:
  GEOMETRIC:
    num_features: 184

  